[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "NeuralNetworks",
    "NNEF",
]
license = "MIT/Apache-2.0"
name = "tract-nnef"
repository = "https://github.com/snipsco/tract"
version = "0.12.3"

[badges.maintenance]
status = "actively-developed"

[dependencies]
byteorder = "1"
log = "0.4"
nom = "5"
tar = "0.4"
tract-core = "0.12.3"
walkdir = "2"

[dependencies.flate2]
optional = true
version = "1.0"

[features]
default = ["flate2"]
