[package]
name = "onnx-test-suite"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
bytes.workspace = true
fs2.workspace = true
log.workspace = true
prost.workspace = true
tract-onnx = { path = "../../onnx" , version = "0.19.0-alpha.8" }

[dependencies.tract-nnef ]
version = "0.19.0-alpha.8"

[dependencies.tract-core ]
version = "0.19.0-alpha.8"

[features]
onnx_1_4_1 = []
onnx_1_5_0 = []
onnx_1_6_0 = []
onnx_1_7_0 = []
onnx_1_8_1 = []
onnx_1_9_0 = []
onnx_1_10_1 = []
default = [ "onnx_1_10_1" ]

[dev-dependencies]
env_logger.workspace = true

[build-dependencies]
fs2.workspace = true
