[package]
name = "core-proptest-pulse"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
tract-hir = { path = "../../hir" , version = "0.19.0-alpha.8" }
tract-onnx-opl = { path = "../../onnx-opl/" , version = "0.19.0-alpha.8" }

[dependencies.tract-pulse ]
version = "0.19.0-alpha.8"

[dependencies.tract-onnx]
version = "0.19.0-alpha.8"

[dev-dependencies]
log.workspace = true
proptest.workspace = true
env_logger.workspace = true
