[package]
name = "tf-mobilenet-v2"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"

[dependencies]
image.workspace = true
tract-tensorflow = { path = "../../tensorflow" , version = "0.19.0-alpha.8" }

[dev-dependencies]
dinghy-test.workspace = true
