[package]
name = "tract"
version = "0.13.1"
authors = [ "Romain Liautaud <romain.liautaud@snips.ai>", "Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "TensorFlow", "NeuralNetworks" ]
categories = [ "science" ]
autobenches = false
edition = "2018"
include = [ "Cargo.toml", "src/**/*.rs" ]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
ansi_term = "0.12.0"
atty = "0.2"
box_drawing = "0.1"
clap = "2.31"
criterion = "0.3"
colorous = "1.0.2"
env_logger = "0.7"
flate2 = "1"
lazy_static = "1.0"
log = "0.4"
ndarray-npy = { version = "0.6", features = [ "compressed_npz" ] }
py_literal = "0.2"
rand = "0.7"
readings-probe = "0.1.1"
regex = "1.3"
serde = "1.0.110"
serde_json = "1.0.53"
serde_derive = "1.0.110"
tract-core = "=0.13.1"
tract-hir = "=0.13.1"
tract-nnef = "=0.13.1"
tract-pulse-opl = { optional = true, version = "=0.13.1" }
tract-pulse = { optional = true, version = "=0.13.1" }
tract-kaldi = { optional = true, version = "=0.13.1" }
tract-onnx = { optional = true, version = "=0.13.1" }
tract-tensorflow = { optional = true, version = "=0.13.1" }

[features]
default = ["kaldi", "onnx", "tf", "pulse", "pulse-opl"]
kaldi = [ "tract-kaldi" ]
onnx = [ "tract-onnx" ]
pulse-opl = [ "tract-pulse-opl" ]
pulse = [ "tract-pulse", "tract-pulse-opl" ]
tf = [ "tract-tensorflow" ]
conform = [ "tract-tensorflow/conform"  ]
