[package]
authors = [
    "Romain Liautaud <romain.liautaud@snips.ai>",
    "Mathieu Poumeyrol <kali@zoy.org>",
]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
include = [
    "Cargo.toml",
    "src/**/*.rs",
]
keywords = [
    "TensorFlow",
    "NeuralNetworks",
]
license = "MIT/Apache-2.0"
name = "tract"
repository = "https://github.com/snipsco/tract"
version = "0.12.3"

[badges.maintenance]
status = "actively-developed"

[dependencies]
ansi_term = "0.12.0"
atty = "0.2"
box_drawing = "0.1"
clap = "2.31"
colorous = "1.0.2"
criterion = "0.3"
env_logger = "0.7"
flate2 = "1"
lazy_static = "1.0"
log = "0.4"
py_literal = "0.2"
rand = "0.7"
readings-probe = "0.1.1"
regex = "1.3"
serde = "1.0.110"
serde_derive = "1.0.110"
serde_json = "1.0.53"
tract-core = "0.12.3"
tract-hir = "0.12.3"
tract-nnef = "0.12.3"

[dependencies.ndarray-npy]
features = ["compressed_npz"]
version = "0.6"

[dependencies.tract-kaldi]
optional = true
version = "0.12.3"

[dependencies.tract-onnx]
optional = true
version = "0.12.3"

[dependencies.tract-pulse]
optional = true
version = "0.12.3"

[dependencies.tract-pulse-opl]
optional = true
version = "0.12.3"

[dependencies.tract-tensorflow]
optional = true
version = "0.12.3"

[features]
conform = ["tract-tensorflow/conform"]
default = [
    "kaldi",
    "onnx",
    "tf",
    "pulse",
    "pulse-opl",
]
kaldi = ["tract-kaldi"]
onnx = ["tract-onnx"]
pulse = [
    "tract-pulse",
    "tract-pulse-opl",
]
pulse-opl = ["tract-pulse-opl"]
tf = ["tract-tensorflow"]
