[package]
name = "jupyter-keras-tract-tf1"
version = "0.1.0"
authors = ["Matthew Alhonte <mattalhonte@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand.workspace = true
tract-tensorflow = { path = "../../tensorflow" , version = "0.19.0-alpha.8" }

[dependencies.tract-core ]
version = "0.19.0-alpha.8"
