[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "TensorFlow",
    "NeuralNetworks",
]
license = "MIT/Apache-2.0"
name = "tract-core"
repository = "https://github.com/snipsco/tract"
version = "0.12.3"

[[bench]]
harness = false
name = "conv_direct_vs_im2col"

[[bench]]
harness = false
name = "wavenet"

[[bench]]
harness = false
name = "im2col_inception"
[badges.maintenance]
status = "actively-developed"

[dependencies]
anyhow = "1"
bit-set = "0.5"
derive-new = "0.5"
downcast-rs = "1.0"
dyn-clone = "1"
educe = "=0.4.11"
half = "1.3"
itertools = "0.9"
lazy_static = "1"
log = "0.4"
maplit = "1"
num-integer = "0.1"
num-traits = "0.2"
smallvec = "1"
tract-data = "0.12.3"
tract-linalg = "0.12.3"

[dependencies.ndarray]
version = "=0.13.0"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.7"
lazy_static = "1"
proptest = "0.10"

[features]
default = []
paranoid_assertions = []
