[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
keywords = [
    "TensorFlow",
    "NeuralNetworks",
    "ONNX",
]
license = "MIT/Apache-2.0"
name = "tract-tensorflow"
repository = "https://github.com/snipsco/tract"
version = "0.12.3"

[badges.maintenance]
status = "actively-developed"

[build-dependencies]
prost-build = "0.6"

[dependencies]
bytes = "0.5"
derive-new = "0.5"
educe = "=0.4.11"
log = "0.4"
prost = "0.6"
prost-types = "0.6"
tract-hir = "0.12.3"
tract-pulse = "0.12.3"

[dependencies.tensorflow]
optional = true
version = "0"

[dev-dependencies]
criterion = "0.3"
env_logger = "0.7"
proptest = "0.10"
rand = "0.7"

[features]
conform = ["tensorflow"]
[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
mapr = "0.8"
