[package]
name = "nnef-inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
flate2.workspace = true
image.workspace = true

[dependencies.tract-nnef ]
version = "0.19.0-alpha.8"

[dependencies.tract-core ]
version = "0.19.0-alpha.8"

[dev-dependencies]
dinghy-test.workspace = true
env_logger.workspace = true
log.workspace = true
