[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
autobenches = false
categories = ["science"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
edition = "2018"
exclude = ["test_cases"]
keywords = [
    "TensorFlow",
    "NeuralNetworks",
    "ONNX",
]
license = "MIT/Apache-2.0"
name = "tract-onnx"
repository = "https://github.com/snipsco/tract"
version = "0.12.3"

[badges.maintenance]
status = "actively-developed"

[build-dependencies]
prost-build = "0.6"

[dependencies]
bytes = "0.5"
derive-new = "0.5"
educe = "=0.4.11"
log = "0.4"
num-integer = "0.1"
prost = "0.6"
smallvec = "1"
tract-hir = "0.12.3"
tract-nnef = "0.12.3"
tract-onnx-opl = "0.12.3"
[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
mapr = "0.8"
